from scipy.linalg import norm as norm
from scipy.sparse import csr_matrix as csr_matrix, eye as eye, rand as rand
from scipy.sparse.linalg import splu as splu
from scipy.sparse.linalg.interface import LinearOperator as LinearOperator
from scipy.sparse.linalg.isolve import gmres as gmres, lgmres as lgmres
from typing import Any

Am: Any
b: Any
count: Any

def matvec(v): ...

A: Any

def do_solve(**kw): ...

class TestLGMRES:
    def test_preconditioner(self) -> None: ...
    def test_outer_v(self) -> None: ...
    def test_arnoldi(self) -> None: ...
    def test_cornercase(self) -> None: ...
    def test_nans(self) -> None: ...
    def test_breakdown_with_outer_v(self) -> None: ...
    def test_breakdown_underdetermined(self) -> None: ...
    def test_denormals(self) -> None: ...
