from scipy.linalg import norm as norm
from scipy.sparse import csr_matrix as csr_matrix, eye as eye, rand as rand
from scipy.sparse.linalg import splu as splu
from scipy.sparse.linalg.interface import LinearOperator as LinearOperator
from scipy.sparse.linalg.isolve import gcrotmk as gcrotmk, gmres as gmres
from typing import Any

Am: Any
b: Any
count: Any

def matvec(v): ...

A: Any

def do_solve(**kw): ...

class TestGCROTMK:
    def test_preconditioner(self) -> None: ...
    def test_arnoldi(self) -> None: ...
    def test_cornercase(self) -> None: ...
    def test_nans(self) -> None: ...
    def test_truncate(self) -> None: ...
    def test_CU(self) -> None: ...
    def test_denormals(self) -> None: ...
