from .sputils import isintlike as isintlike
from typing import Any

INT_TYPES: Any

class IndexMixin:
    def __getitem__(self, key): ...
    def __setitem__(self, key, x) -> None: ...
    def getrow(self, i): ...
    def getcol(self, i): ...
