from .base import spmatrix as spmatrix
from .sputils import isscalarlike as isscalarlike, matrix as matrix, validateaxis as validateaxis
from typing import Any

class _data_matrix(spmatrix):
    def __init__(self) -> None: ...
    dtype: Any
    def __abs__(self): ...
    def __round__(self, ndigits: int = ...): ...
    def __neg__(self): ...
    def __imul__(self, other): ...
    def __itruediv__(self, other): ...
    def astype(self, dtype, casting: str = ..., copy: bool = ...): ...
    def conj(self, copy: bool = ...): ...
    def copy(self): ...
    def count_nonzero(self): ...
    def power(self, n, dtype: Any | None = ...): ...

name: Any

class _minmax_mixin:
    def max(self, axis: Any | None = ..., out: Any | None = ...): ...
    def min(self, axis: Any | None = ..., out: Any | None = ...): ...
    def argmax(self, axis: Any | None = ..., out: Any | None = ...): ...
    def argmin(self, axis: Any | None = ..., out: Any | None = ...): ...
