from .data import _data_matrix
from typing import Any

class dia_matrix(_data_matrix):
    format: str
    data: Any
    offsets: Any
    def __init__(self, arg1, shape: Any | None = ..., dtype: Any | None = ..., copy: bool = ...) -> None: ...
    def count_nonzero(self): ...
    def getnnz(self, axis: Any | None = ...): ...
    def sum(self, axis: Any | None = ..., dtype: Any | None = ..., out: Any | None = ...): ...
    def todia(self, copy: bool = ...): ...
    def transpose(self, axes: Any | None = ..., copy: bool = ...): ...
    def diagonal(self, k: int = ...): ...
    def tocsc(self, copy: bool = ...): ...
    def tocoo(self, copy: bool = ...): ...
    def resize(self, *shape) -> None: ...

def isspmatrix_dia(x): ...
