from ._index import IndexMixin
from .base import spmatrix
from typing import Any

class dok_matrix(spmatrix, IndexMixin, dict):
    format: str
    dtype: Any
    def __init__(self, arg1, shape: Any | None = ..., dtype: Any | None = ..., copy: bool = ...) -> None: ...
    def update(self, val) -> None: ...
    __dict__: Any
    def set_shape(self, shape) -> None: ...
    shape: Any
    def getnnz(self, axis: Any | None = ...): ...
    def count_nonzero(self): ...
    def __len__(self): ...
    def get(self, key, default: float = ...): ...
    def __add__(self, other): ...
    def __radd__(self, other): ...
    def __neg__(self): ...
    def __imul__(self, other): ...
    def __truediv__(self, other): ...
    def __itruediv__(self, other): ...
    def __reduce__(self): ...
    def transpose(self, axes: Any | None = ..., copy: bool = ...): ...
    def conjtransp(self): ...
    def copy(self): ...
    def tocoo(self, copy: bool = ...): ...
    def todok(self, copy: bool = ...): ...
    def tocsc(self, copy: bool = ...): ...
    def resize(self, *shape) -> None: ...

def isspmatrix_dok(x): ...
