from scipy.sparse import csc_matrix as csc_matrix, csr_matrix as csr_matrix
from scipy.sparse.csgraph import maximum_flow as maximum_flow

def test_raises_on_dense_input() -> None: ...
def test_raises_on_csc_input() -> None: ...
def test_raises_on_floating_point_input() -> None: ...
def test_raises_when_source_is_sink() -> None: ...
def test_raises_when_source_is_out_of_bounds(source) -> None: ...
def test_raises_when_sink_is_out_of_bounds(sink) -> None: ...
def test_simple_graph() -> None: ...
def test_bottle_neck_graph() -> None: ...
def test_backwards_flow() -> None: ...
def test_example_from_clrs_chapter_26_1() -> None: ...
def test_disconnected_graph() -> None: ...
