from typing import Any, Union
from networkx.classes import Graph, DiGraph
DiGraphOrGraph = Union[Graph, DiGraph]
def relabel_nodes(DiGraphOrGraph, mapping, copy: bool = ...): ...
def convert_node_labels_to_integers(G, first_label: int = ..., ordering: str = ..., label_attribute: Any | None = ...): ...
