from scipy.sparse import csr_matrix as csr_matrix, extract as extract
from typing import Any

class TestExtract:
    cases: Any
    def setup_method(self) -> None: ...
    def find(self) -> None: ...
    def test_tril(self) -> None: ...
    def test_triu(self) -> None: ...
