from collections.abc import Generator
from typing import Any
from networkx import DiGraph

def weakly_connected_components(DiGraph) -> Generator[Any, None, None]: ...
def number_weakly_connected_components(DiGraph): ...
def is_weakly_connected(DiGraph)-> bool: ...
