from typing import Any

def bicg(A, b, x0: Any | None = ..., tol: float = ..., maxiter: Any | None = ..., M: Any | None = ..., callback: Any | None = ..., atol: Any | None = ...): ...
def bicgstab(A, b, x0: Any | None = ..., tol: float = ..., maxiter: Any | None = ..., M: Any | None = ..., callback: Any | None = ..., atol: Any | None = ...): ...
def cg(A, b, x0: Any | None = ..., tol: float = ..., maxiter: Any | None = ..., M: Any | None = ..., callback: Any | None = ..., atol: Any | None = ...): ...
def cgs(A, b, x0: Any | None = ..., tol: float = ..., maxiter: Any | None = ..., M: Any | None = ..., callback: Any | None = ..., atol: Any | None = ...): ...
def gmres(A, b, x0: Any | None = ..., tol: float = ..., restart: Any | None = ..., maxiter: Any | None = ..., M: Any | None = ..., callback: Any | None = ..., restrt: Any | None = ..., atol: Any | None = ..., callback_type: Any | None = ...): ...
def qmr(A, b, x0: Any | None = ..., tol: float = ..., maxiter: Any | None = ..., M1: Any | None = ..., M2: Any | None = ..., callback: Any | None = ..., atol: Any | None = ...): ...
