from typing import Any

def lgmres(A, b, x0: Any | None = ..., tol: float = ..., maxiter: int = ..., M: Any | None = ..., callback: Any | None = ..., inner_m: int = ..., outer_k: int = ..., outer_v: Any | None = ..., store_outer_Av: bool = ..., prepend_outer_v: bool = ..., atol: Any | None = ...): ...
