from typing import Any

def lsqr(A, b, damp: float = ..., atol: float = ..., btol: float = ..., conlim: float = ..., iter_lim: Any | None = ..., show: bool = ..., calc_var: bool = ..., x0: Any | None = ...): ...
