from typing import Any

def minres(A, b, x0: Any | None = ..., shift: float = ..., tol: float = ..., maxiter: Any | None = ..., M: Any | None = ..., callback: Any | None = ..., show: bool = ..., check: bool = ...): ...
