from scipy.sparse.linalg.interface import IdentityOperator as IdentityOperator, LinearOperator as LinearOperator, aslinearoperator as aslinearoperator
from scipy.sparse.sputils import asmatrix as asmatrix

__docformat__: str

def coerce(x, y): ...
def id(x): ...
def make_system(A, M, x0, b): ...
