from typing import Any

class MatrixRankWarning(UserWarning): ...

def use_solver(**kwargs) -> None: ...
def spsolve(A, b, permc_spec: Any | None = ..., use_umfpack: bool = ...): ...
def splu(A, permc_spec: Any | None = ..., diag_pivot_thresh: Any | None = ..., relax: Any | None = ..., panel_size: Any | None = ..., options=...): ...
def spilu(A, drop_tol: Any | None = ..., fill_factor: Any | None = ..., drop_rule: Any | None = ..., permc_spec: Any | None = ..., diag_pivot_thresh: Any | None = ..., relax: Any | None = ..., panel_size: Any | None = ..., options: Any | None = ...): ...
def factorized(A): ...
def spsolve_triangular(A, b, lower: bool = ..., overwrite_A: bool = ..., overwrite_b: bool = ..., unit_diagonal: bool = ...): ...
