from typing import Any

def expm_multiply(A, B, start: Any | None = ..., stop: Any | None = ..., num: Any | None = ..., endpoint: Any | None = ...): ...

class LazyOperatorNormInfo:
    def __init__(self, A, A_1_norm: Any | None = ..., ell: int = ..., scale: int = ...) -> None: ...
    def set_scale(self, scale) -> None: ...
    def onenorm(self): ...
    def d(self, p): ...
    def alpha(self, p): ...
