from typing import Any

class LinearOperator:
    ndim: int
    def __new__(cls, *args, **kwargs): ...
    dtype: Any
    shape: Any
    def __init__(self, dtype, shape) -> None: ...
    def matvec(self, x): ...
    def rmatvec(self, x): ...
    def matmat(self, X): ...
    def rmatmat(self, X): ...
    def __call__(self, x): ...
    def __mul__(self, x): ...
    def dot(self, x): ...
    def __matmul__(self, other): ...
    def __rmatmul__(self, other): ...
    def __rmul__(self, x): ...
    def __pow__(self, p): ...
    def __add__(self, x): ...
    def __neg__(self): ...
    def __sub__(self, x): ...
    def adjoint(self): ...
    H: Any
    def transpose(self): ...
    T: Any

class _CustomLinearOperator(LinearOperator):
    args: Any
    def __init__(self, shape, matvec, rmatvec: Any | None = ..., matmat: Any | None = ..., dtype: Any | None = ..., rmatmat: Any | None = ...) -> None: ...

class _AdjointLinearOperator(LinearOperator):
    A: Any
    args: Any
    def __init__(self, A) -> None: ...

class _TransposedLinearOperator(LinearOperator):
    A: Any
    args: Any
    def __init__(self, A) -> None: ...

class _SumLinearOperator(LinearOperator):
    args: Any
    def __init__(self, A, B) -> None: ...

class _ProductLinearOperator(LinearOperator):
    args: Any
    def __init__(self, A, B) -> None: ...

class _ScaledLinearOperator(LinearOperator):
    args: Any
    def __init__(self, A, alpha) -> None: ...

class _PowerLinearOperator(LinearOperator):
    args: Any
    def __init__(self, A, p) -> None: ...

class MatrixLinearOperator(LinearOperator):
    A: Any
    args: Any
    def __init__(self, A) -> None: ...

class _AdjointMatrixOperator(MatrixLinearOperator):
    A: Any
    args: Any
    shape: Any
    def __init__(self, adjoint) -> None: ...
    @property
    def dtype(self): ...

class IdentityOperator(LinearOperator):
    def __init__(self, shape, dtype: Any | None = ...) -> None: ...

def aslinearoperator(A): ...
